version: '2.1'

services:
  influxdb:
    image: hypriot/rpi-influxdb:latest
    restart: always
    volumes:
      - /mnt/picluster/influxdb:/data
      -/mnt/picluster/influxdb/config:/etc/infuxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      INFLUXDB_GRAPHITE_ENABLED: 'true'
      INFLUXDB_REPORTING_DISABLED: 'true'
  grafana:
    image: fg2it/grafana-armhf:v4.3.2
    restart: always
    depends_on:
      - influxdb
    links:
      - influxdb
    volumes:
      - /mnt/picluster/grafana/log:/var/log/grafana
      - /mnt/picluster/grafana/data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    environment:
      # the login for the web-interface on port 3000 will be admin/secret
      GF_SECURITY_ADMIN_PASSWORD: 'Dfdbkjy-5'
      GF_INSTALL_PLUGINS: 'grafana-worldmap-panel,grafana-piechart-panel,briangann-gauge-panel,natel-discrete-panel,natel-influx-admin-panel,briangann-datatable-panel'
