version: '1.0'

services:
  influxdb:
    image: hypriot/rpi-influxdb:latest
    restart: always
    volumes:
      - <your path for influxDb>:/data
      - <your path for influxDb config>:/etc/infuxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      INFLUXDB_GRAPHITE_ENABLED: 'true'
      INFLUXDB_REPORTING_DISABLED: 'true'
  grafana:
    image: fg2it/grafana-armhf:v4.3.2
    restart: always
    depends_on:
      - influxdb
    links:
      - influxdb
    volumes:
      - <your path for grafana>/log:/var/log/grafana
      - <your path for grafana>/data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    environment:
      # the login for the web-interface on port 3000 will be admin/secret
      GF_SECURITY_ADMIN_PASSWORD: '<your grafaba admin passwd>'
